### ISSUE TITLE
GStreamer Source appears in Audio Mixer with audio. disconnected

### ISSUE THREAD

**Issue by crossan007** [fzwoch/obs-gstreamer#2]
A GStreamer Source appears in the OBS audio mixer, even when no GStreamer Source instances have connections to the `audio.` pad.

**Comment by fzwoch** [comment]
When loading the plugin from OBS we have to announce our capabilities. Since we generally want to allow audio to be feed into OBS we also announce ourselves as an audio source too. Since we don't know anything about hte pipeline at this point we can't react to it. And we cannot change our capabilities after the plugin is loaded (as far as I know).

**Comment by fzwoch** [comment]
Closing for now unless someone knows if there is another way. In the meantime I think one can just remove the mixer of this source from the scene in OBS.
