### ISSUE TITLE
[build] [aarch64] make install installs in the wrong location

### ISSUE THREAD

**Issue by pgwipeout** [fzwoch/obs-gstreamer#31]
Running the `sudo ninja -C build install ` on aarch64 installs to `/usr/local/lib/aarch64-linux-gnu/obs-plugins`.
When building OBS native on aarch64  the required installation location is the standard `/usr/lib/obs-plugins`.

**Comment by fzwoch** [comment]
There is no way to do the right thing for everyone. Some people even may have OBS installed via their system and also manually compiled. Both can co-exist and it is not obvious for which version this plugin is to be installed.

So the problem is offloaded to meson and the user. It will install into the `obs-plugins` directory inside whatever `libdir` in meson is set to.

E.g.

```
meson --buildtype=release --libdir=lib
```

will install at `/usr/local/lib/obs-plugins`.

If you want it to install outside of `/usr/local` you will have to set a `prefix` as well.

E.g.

```
meson --buildtype=release --libdir=lib --prefix=/usr
```

You can also make it install in your user home directory (wherever that directory was exactly..)

**Comment by pgwipeout** [comment]
Hey that's perfect!
Could we just update the readme with that info then?
